// src/views/Pricing.vue
<template>
  <section class="pricing-page">
    <div class="background"></div>

    <div class="panel hero">
      <div>
        <p class="eyebrow">Henna By Rachana</p>
        <h1>Pricing & Packages</h1>
        <p class="lede">
          Now styled to match the green studio palette. Choose a package or build your own based on coverage,
          with clear visuals for exactly how far the design goes.
        </p>
        <div class="chips">
          <span class="chip">Travel-friendly</span>
          <span class="chip">Custom designs on request</span>
          <span class="chip">Both hands or full bridal</span>
        </div>
      </div>
    </div>

    <div class="panel packages">
      <div class="panel-heading">
        <h2>Packages</h2>
        <p>Mirror of the shared reference: clear columns for coverage, price, and inclusions.</p>
      </div>
      <div class="table">
        <div class="row head">
          <div class="cell">Packages</div>
          <div class="cell">Areas Covered</div>
          <div class="cell price-col">Price</div>
        </div>
        <div v-for="item in packages" :key="item.name" class="row">
          <div class="cell name">
            <span class="icon">✦</span>
            <div>
              <div class="title">{{ item.name }}</div>
              <div class="subtitle" v-if="item.subtitle">{{ item.subtitle }}</div>
            </div>
          </div>
          <div class="cell description">
            <span v-html="item.coverage"></span>
          </div>
          <div class="cell price-col">
            <span class="pill">{{ item.price }}</span>
          </div>
        </div>
      </div>
      <ul class="notes">
        <li>Prices may vary based on design complexity.</li>
        <li>Both legs include minimal design to echo the reference layout.</li>
      </ul>
    </div>

    <div class="panel ala-carte">
      <div class="panel-heading">
        <h2>Henna by Area (One Side)</h2>
        <p>Use these to mix and match coverage — styled after the provided visual guide.</p>
      </div>
      <div class="cards">
        <article v-for="item in alaCarte" :key="item.name" class="card-item">
          <div class="badge">{{ item.step }}</div>
          <div class="card-body">
            <div class="card-title">{{ item.name }}</div>
            <div class="card-sub">{{ item.detail }}</div>
          </div>
          <div class="card-price">{{ item.price }}</div>
        </article>
      </div>
      <figure class="coverage-figure card">
        <img :src="coverageImage" alt="One-side henna pricing reference with hand illustration" />
        <figcaption>Reference visual exactly as provided — shows wrist, mid arm, elbow, and above elbow coverage.</figcaption>
      </figure>
      <ul class="notes">
        <li>Prices may vary based on design complexity.</li>
        <li>Both sides available on request.</li>
        <li>Bridal and custom designs are priced separately.</li>
      </ul>
    </div>
  </section>
</template>

<script setup>
const packages = [
  {
    name: 'Standard Package',
    subtitle: '',
    coverage: 'Both hands till 1/2 arm length + minimal design on both legs',
    price: '€150'
  },
  {
    name: 'Premium Package',
    subtitle: '',
    coverage: 'Both hands till elbow length + minimal design on both legs',
    price: '€250'
  },
  {
    name: 'Bridal Package',
    subtitle: '',
    coverage: 'Both hands above elbow length + minimal design on both legs',
    price: '€350'
  }
]

const alaCarte = [
  { step: '1', name: 'Wrist', detail: 'One side', price: '€10' },
  { step: '2', name: 'Mid Arm', detail: 'One side', price: '€30' },
  { step: '3', name: 'Elbow', detail: 'One side', price: '€60' },
  { step: '4', name: 'Above Elbow', detail: 'One side', price: '€100' }
]

// Use the original map.jpeg for the one-side coverage visual
const coverageImage = '/media/designs/map.jpeg'
</script>

<style scoped>
.pricing-page {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 24px;
  color: var(--text);
}

.background {
  position: absolute;
  inset: 0;
  z-index: 0;
  background: radial-gradient(circle at 18% 20%, rgba(33, 103, 83, 0.35), transparent 32%),
    radial-gradient(circle at 78% 10%, rgba(20, 64, 50, 0.35), transparent 30%),
    linear-gradient(135deg, #0f3d2e, #173f35 45%, #0f3d2e);
  opacity: 0.96;
  border-radius: 22px;
}

.panel {
  position: relative;
  z-index: 1;
  background: rgba(17, 66, 53, 0.9);
  border: 1px solid var(--border);
  border-radius: 18px;
  padding: 22px 24px;
  box-shadow: 0 18px 40px rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(3px);
}

.hero {
  display: grid;
  grid-template-columns: 1.4fr 1fr;
  gap: 18px;
  align-items: center;
}

.eyebrow {
  letter-spacing: 0.3em;
  text-transform: uppercase;
  font-size: 12px;
  color: var(--muted);
  margin: 0 0 6px;
}

h1 {
  margin: 0;
  color: var(--text);
  font-size: clamp(28px, 5vw, 40px);
}

.lede {
  margin: 10px 0 12px;
  color: var(--muted);
  line-height: 1.5;
}

.chips {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.chip {
  background: var(--card);
  color: var(--text);
  padding: 8px 12px;
  border-radius: 999px;
  border: 1px solid var(--border);
  font-weight: 600;
}

.seal {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: var(--muted);
  color: #0f3d2e;
  font-weight: 800;
  padding: 6px 12px;
  border-radius: 12px;
  border: 1px solid rgba(0, 0, 0, 0.2);
  margin-bottom: 8px;
}

.mini-note {
  margin-top: 6px;
  color: var(--text);
  font-size: 14px;
  opacity: 0.9;
}

.coverage-figure {
  margin-top: 14px;
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 14px;
  overflow: hidden;
  padding: 0;
}

.coverage-figure img {
  display: block;
  width: 70%;
  height: auto;
  object-fit: cover;
  margin: 0 auto;
}

.coverage-figure figcaption {
  padding: 10px 12px;
  color: var(--muted);
  font-size: 14px;
}

.panel-heading h2 {
  margin: 0;
  color: var(--text);
}

.panel-heading p {
  margin: 6px 0 12px;
  color: var(--muted);
}

.table {
  display: grid;
  gap: 8px;
}

.row {
  display: grid;
  grid-template-columns: 1fr 1.4fr 0.5fr;
  align-items: center;
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 12px 14px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.25);
}

.row.head {
  background: #0f3d2e;
  box-shadow: none;
  font-weight: 700;
  color: var(--text);
}

.cell {
  color: var(--text);
  display: flex;
  align-items: center;
  gap: 8px;
}

.name .title { font-weight: 700; }
.name .subtitle { color: var(--muted); font-size: 14px; }

.icon {
  width: 26px;
  height: 26px;
  display: grid;
  place-items: center;
  background: #0f3d2e;
  border-radius: 10px;
  color: var(--muted);
  font-size: 14px;
}

.description { line-height: 1.45; }

.price-col { justify-content: flex-end; }

.pill {
  background: var(--muted);
  color: #0f3d2e;
  padding: 10px 14px;
  border-radius: 999px;
  border: 1px solid rgba(0, 0, 0, 0.15);
  font-weight: 700;
}

.notes {
  margin: 12px 0 0;
  padding-left: 18px;
  color: var(--muted);
  line-height: 1.4;
}

.ala-carte .cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px;
}

.card-item {
  position: relative;
  display: grid;
  grid-template-columns: auto 1fr auto;
  align-items: center;
  gap: 12px;
  padding: 14px 16px;
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 12px;
  box-shadow: 0 10px 26px rgba(0, 0, 0, 0.2);
}

.badge {
  width: 32px;
  height: 32px;
  display: grid;
  place-items: center;
  background: #0f3d2e;
  color: var(--muted);
  font-weight: 800;
  border-radius: 10px;
}

.card-title { font-weight: 700; color: var(--text); }
.card-sub { color: var(--muted); font-size: 14px; }

.card-price {
  font-weight: 800;
  color: #0f3d2e;
  background: var(--muted);
  padding: 8px 12px;
  border-radius: 10px;
  border: 1px solid rgba(0, 0, 0, 0.15);
}

@media (max-width: 820px) {
  .hero { grid-template-columns: 1fr; }
  .row { grid-template-columns: 1fr; gap: 6px; align-items: flex-start; }
  .price-col { justify-content: flex-start; }
  .table .row.head { display: none; }
  .cell { align-items: flex-start; }
}

@media (max-width: 720px) {
  .pricing-page { gap: 16px; }
  .panel { padding: 16px 14px; border-radius: 14px; }
  .ala-carte .cards { grid-template-columns: 1fr; }
  .card-item { padding: 12px 14px; }
  .card-price { padding: 6px 10px; font-size: 14px; }
  .coverage-figure img { width: 100%; }
  .coverage-figure figcaption { font-size: 13px; padding: 10px; }
  .chips { gap: 8px; }
  .chip { padding: 6px 10px; font-size: 13px; }
}
</style>

// app/src/components/Pricing.jsx
import { motion } from 'framer-motion'

const packages = [
  { name: 'Standard Package', coverage: 'Both hands till 1/2 arm length + minimal design on both legs', price: '€150' },
  { name: 'Premium Package', coverage: 'Both hands till elbow length + minimal design on both legs', price: '€250' },
  { name: 'Bridal Package', coverage: 'Both hands above elbow length + minimal design on both legs', price: '€350' }
]

const alaCarte = [
  { step: '1', name: 'Wrist', detail: 'One side', price: '€10' },
  { step: '2', name: 'Mid Arm', detail: 'One side', price: '€30' },
  { step: '3', name: 'Elbow', detail: 'One side', price: '€60' },
  { step: '4', name: 'Above Elbow', detail: 'One side', price: '€100' }
]

const fade = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: '-60px' },
  transition: { duration: 0.6 }
}

export default function Pricing() {
  return (
    <section id="pricing" className="relative py-24 px-6 md:px-10">
      <div className="container-x flex flex-col gap-6">
        <motion.div {...fade} className="card p-6 md:p-8 grid md:grid-cols-[1.4fr_1fr] gap-5 items-center">
          <div>
            <p className="text-xs tracking-[0.3em] uppercase text-muted mb-2">Henna By Rachana</p>
            <h2 className="text-3xl md:text-4xl font-extrabold">Pricing & Packages</h2>
            <p className="text-muted mt-3 leading-relaxed">
              Clear coverage, clear prices. Choose a package or build your own based on coverage.
            </p>
            <div className="flex flex-wrap gap-2 mt-4">
              {['Travel-friendly', 'Custom designs on request', 'Both hands or full bridal'].map((c) => (
                <span key={c} className="px-3 py-1.5 rounded-full border border-border bg-card text-text font-semibold text-sm">{c}</span>
              ))}
            </div>
          </div>
        </motion.div>

        <motion.div {...fade} className="card p-6 md:p-8">
          <h3 className="text-2xl font-extrabold">Packages</h3>
          <p className="text-muted mt-1 mb-4">Coverage, price and inclusions.</p>

          <div className="grid gap-2">
            <div className="hidden md:grid grid-cols-[1fr_1.4fr_0.5fr] bg-bg rounded-xl px-4 py-3 font-bold">
              <div>Packages</div>
              <div>Areas Covered</div>
              <div className="text-right">Price</div>
            </div>
            {packages.map((p, i) => (
              <motion.div
                key={p.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-40px' }}
                transition={{ duration: 0.5, delay: i * 0.08 }}
                className="grid md:grid-cols-[1fr_1.4fr_0.5fr] gap-2 bg-card border border-border rounded-xl px-4 py-3 shadow-[0_8px_20px_rgba(0,0,0,0.25)]"
              >
                <div className="flex items-center gap-2">
                  <span className="w-6 h-6 grid place-items-center bg-bg rounded-[10px] text-muted text-sm">✦</span>
                  <span className="font-bold">{p.name}</span>
                </div>
                <div className="leading-snug">{p.coverage}</div>
                <div className="md:text-right">
                  <span className="bg-muted text-[#0f3d2e] px-3 py-2 rounded-full font-bold">{p.price}</span>
                </div>
              </motion.div>
            ))}
          </div>

          <ul className="mt-4 pl-5 list-disc text-muted leading-relaxed">
            <li>Prices may vary based on design complexity.</li>
            <li>Both legs include minimal design to echo the reference layout.</li>
          </ul>
        </motion.div>

        <motion.div {...fade} className="card p-6 md:p-8">
          <h3 className="text-2xl font-extrabold">Henna by Area (One Side)</h3>
          <p className="text-muted mt-1 mb-4">Mix and match coverage by area.</p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            {alaCarte.map((it, i) => (
              <motion.article
                key={it.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-40px' }}
                transition={{ duration: 0.5, delay: i * 0.08 }}
                className="grid grid-cols-[auto_1fr_auto] items-center gap-3 p-4 bg-card border border-border rounded-xl shadow-[0_10px_26px_rgba(0,0,0,0.2)]"
              >
                <div className="w-8 h-8 grid place-items-center bg-bg rounded-[10px] text-muted font-extrabold">{it.step}</div>
                <div>
                  <div className="font-bold">{it.name}</div>
                  <div className="text-muted text-sm">{it.detail}</div>
                </div>
                <div className="font-extrabold bg-muted text-[#0f3d2e] px-3 py-1.5 rounded-[10px] border border-black/15">{it.price}</div>
              </motion.article>
            ))}
          </div>

          <figure className="card mt-5 p-0 overflow-hidden">
            <img src="/media/designs/map.jpeg" alt="One-side henna pricing reference" className="block w-[70%] h-auto mx-auto" />
            <figcaption className="px-3 py-2 text-muted text-sm">
              Reference visual — wrist, mid arm, elbow, and above elbow coverage.
            </figcaption>
          </figure>

          <ul className="mt-4 pl-5 list-disc text-muted leading-relaxed">
            <li>Prices may vary based on design complexity.</li>
            <li>Both sides available on request.</li>
            <li>Bridal and custom designs are priced separately.</li>
          </ul>
        </motion.div>
      </div>
    </section>
  )
}
